name: ChestShops
version: '${project.version}'
main: com.github.gavvydizzle.chestshops.ChestShops
api-version: 1.19
authors: [GavvyDizzle]
depend: [DecentHolograms, InteractiveChat, RentableRegions, ServerUtils, Vault, WorldGuard]
commands:
  chestshopsadmin:
    description: Admin commands for ChestShops
    permission: chestshops.admin
  chestshops:
    description: Player commands for ChestShops
    permission: chestshops.player
